"""Regression tests for ped/merge_ped_scores.py, using REAL VEDA4 output as
ground truth -- data/ved/CH4.ved + CH4.vdf are genuine veda4e1.exe GUI output
(the first real fchk-framework VEDA4 pass in this repo, see ped/README.md),
not a synthetic fixture. data/results/CH4_normal_classified.csv is likewise
this repo's own real pipeline output for the same molecule/geometry.

Run from ``Github/scoring-functions/``:
    py -m pytest tests/test_merge_ped_scores.py
    py tests/test_merge_ped_scores.py       (standalone; no pytest needed)
"""
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "ped"))

import merge_ped_scores as mps  # noqa: E402

CH4_VED = os.path.join(ROOT, "data", "ved", "CH4.ved")
CH4_VDF = os.path.join(ROOT, "data", "ved", "CH4.vdf")
CH4_CLASSIFIED = os.path.join(ROOT, "data", "results", "CH4_normal_classified.csv")


def _require(*paths):
    missing = [p for p in paths if not os.path.isfile(p)]
    if missing:
        raise AssertionError(
            f"Required real-data fixture(s) missing: {missing}. CH4.ved/.vdf "
            "should already be committed to data/ved/; CH4_normal_classified.csv "
            "is regenerated by `python main.py -m CH4 --classify --mode normal`.")


# ---------------------------------------------------------------------------
# parse_ved / parse_coord_types against the real CH4 .ved/.vdf pair
# ---------------------------------------------------------------------------

def test_parse_ved_ch4_shape_and_frequencies():
    _require(CH4_VED)
    freqs, ped = mps.parse_ved(CH4_VED)
    assert len(freqs) == 9
    assert ped.shape == (9, 9)
    # VEDA4's own row order for CH4: triple-degenerate stretch first, then
    # the non-degenerate stretch, then the two degenerate bend sets.
    expected = [3194.70, 3194.70, 3194.70, 3086.49, 1667.80, 1667.80,
                1456.69, 1456.69, 1456.69]
    assert np.allclose(freqs, expected, atol=0.01)


def test_parse_ved_ch4_ped_rows_abs_sum_near_100():
    _require(CH4_VED)
    _freqs, ped = mps.parse_ved(CH4_VED)
    # Raw signed PED rows do NOT reliably sum to 100 for the degenerate
    # 1456.69 cm^-1 triple (e.g. row 7 signed-sums to -98, a known artifact
    # of arbitrary rotation within a degenerate eigenspace) -- but abs()
    # summed first, every row recovers ~100, matching how %PED is
    # conventionally reported (see merge_ped_scores.py module docstring).
    row_sums = np.abs(ped).sum(axis=1)
    assert np.allclose(row_sums, 100.0, atol=2.0), row_sums


def test_parse_coord_types_ch4():
    _require(CH4_VDF)
    types = mps.parse_coord_types(CH4_VDF)
    # From the real CH4.vdf 'definitions of modes' section: s1-3 STRE (CH),
    # s4 STRE (CH), s5-6 BEND (HCH), s7 BEND (HCH), s8-9 OUT (CHHH).
    assert types == ["STRE", "STRE", "STRE", "STRE", "BEND", "BEND",
                      "BEND", "OUT", "OUT"]


def test_compute_ped_percentages_ch4_stretch_vs_bend():
    _require(CH4_VED, CH4_VDF)
    ped_df = mps.compute_ped_percentages(CH4_VED, CH4_VDF)
    assert len(ped_df) == 9
    # Rows 0-3 (the two CH-stretch frequency groups, 3194.70 x3 + 3086.49)
    # must be dominated by stretch character.
    assert (ped_df['PED_Stretch_pct'].iloc[0:4] > 95).all()
    assert (ped_df['PED_Bend_pct'].iloc[0:4] < 5).all()
    # Rows 4-8 (the two bend frequency groups, 1667.80 x2 + 1456.69 x3) must
    # be dominated by bend character (BEND+OUT, per the STRE-only-stretch rule).
    assert (ped_df['PED_Bend_pct'].iloc[4:9] > 95).all()
    assert (ped_df['PED_Stretch_pct'].iloc[4:9] < 5).all()


# ---------------------------------------------------------------------------
# match_modes_by_frequency
# ---------------------------------------------------------------------------

def test_match_modes_by_frequency_identity():
    freqs = [1456.68, 1456.68, 1456.68, 1667.79, 1667.79, 3086.46,
             3194.67, 3194.67, 3194.67]
    assignment = mps.match_modes_by_frequency(freqs, freqs)
    assert len(assignment) == len(freqs)
    for ci, (vi, resid) in assignment.items():
        assert resid == 0.0
    # one-to-one: every classified index and every veda index used exactly once
    assert sorted(assignment.keys()) == list(range(len(freqs)))
    assert sorted(vi for vi, _ in assignment.values()) == list(range(len(freqs)))


def test_match_modes_by_frequency_count_mismatch_raises():
    raised = False
    try:
        mps.match_modes_by_frequency([1.0, 2.0, 3.0], [1.0, 2.0])
    except ValueError:
        raised = True
    assert raised


def test_match_modes_by_frequency_warns_over_tolerance(capsys):
    mps.match_modes_by_frequency([100.0], [105.0], tol=2.0)
    captured = capsys.readouterr()
    assert "WARNING" in captured.out


# ---------------------------------------------------------------------------
# merge_molecule_ped end-to-end on real CH4 data
# ---------------------------------------------------------------------------

def test_merge_molecule_ped_ch4_end_to_end():
    _require(CH4_VED, CH4_VDF, CH4_CLASSIFIED)
    df, vib_rows, out_path = mps.merge_molecule_ped("CH4", repo_root=ROOT, write=False)

    assert out_path.endswith("CH4_normal_classified_ped.csv")
    assert "PED_Stretch_pct" in df.columns
    assert "PED_Bend_pct" in df.columns
    # Exactly two new columns were appended -- nothing else changed shape-wise.
    assert len(vib_rows) == 9

    # The two ideal-reference rows (Tx.. and Rx..) carry NaN PED (no PED exists
    # for a synthetic reference mode).
    tx_row = df[df['Mode'] == 'Tx'].iloc[0]
    assert np.isnan(tx_row['PED_Stretch_pct'])
    assert np.isnan(tx_row['PED_Bend_pct'])

    by_mode = {r['Mode']: r for r in vib_rows}
    # Qualitative cross-check (this module's whole point): the two real
    # CH-stretch mode groups (~3086/~3195 cm^-1, V_Stretch label 'S') should
    # show high PED_Stretch_pct; the bending modes (~1457/~1668 cm^-1, label
    # 'B') should show high PED_Bend_pct and much lower V_Stretch.
    for label, row in by_mode.items():
        if 3000 < row['Freq'] < 3300:
            assert row['label'] == 'S'
            assert row['V_Stretch'] > 0.9
            assert row['PED_Stretch_pct'] > 90
        elif 1400 < row['Freq'] < 1700:
            assert row['label'] == 'B'
            assert row['V_Stretch'] < 0.1
            assert row['PED_Bend_pct'] > 90

    # Frequency matching landed well within tolerance (real VEDA4 recomputed
    # frequencies vs. Gaussian's originals, sub-cm^-1 in this real dataset).
    for r in vib_rows:
        assert r['Freq_Residual_cm-1'] < mps.DEFAULT_FREQ_TOL_CM1


if __name__ == "__main__":
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_") and callable(v)]
    passed = 0
    for fn in tests:
        try:
            if "capsys" in fn.__code__.co_varnames[:fn.__code__.co_argcount]:
                print(f"SKIP  {fn.__name__} (needs pytest's capsys fixture)")
                continue
            fn()
            print(f"PASS  {fn.__name__}")
            passed += 1
        except AssertionError as e:
            print(f"FAIL  {fn.__name__}: {e}")
        except Exception as e:  # noqa: BLE001
            print(f"ERROR {fn.__name__}: {type(e).__name__}: {e}")
    print(f"\n{passed}/{len(tests)} passed")
    sys.exit(0 if passed == len([t for t in tests if 'capsys' not in t.__code__.co_varnames[:t.__code__.co_argcount]]) else 1)
