"""Generate longtable LaTeX fragments for the JCC Supporting Information from
the program's own data/results/*.csv -- for lead-author's JCC_SI_main.tex to
\\input{}. Pure formatting: no new scoring/classification logic and no
recomputation, every number here already exists in a results CSV.

    python -m src.si_tables            # regenerate all fragments

One function per dataset (`water_table`, `library_table`,
`benzene_normal_table`, `benzene_emit_table`, `benzene_emit_summary_table`,
`transferability_misclassified_table`), each:
  1. reads the corresponding CSV with pandas,
  2. trims to a human-readable column subset -- molecule/mode label, freq,
     predicted label, the relevant s[T]/s[R]/s[V_S]/s^{AB} scores, irrep --
     dropping internal/debug columns (d_CA, v_weighting, ref_key, PED_*,
     BondScore_*; full raw CSVs stay in the public repo per the Data
     Availability Statement, noted as a table footnote),
  3. writes a booktabs-style `longtable` fragment (with \\endfirsthead/
     \\endhead for multi-page continuation) to JCC/JCC_SI/tables/.

The master document must load `longtable`, `booktabs`, and (for the
benzene-EMIT fragment, which is wrapped in a `landscape` block -- 38 columns
do not fit portrait even at \\tiny) `pdflscape`.
"""

import os
import pandas as pd

from src.classifier import predicted_category

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_DATA_DIR = os.path.join(REPO_ROOT, "data")
# Two levels up from Github/scoring-functions/ is the OneDrive project root
# (mirrors reproduce.py's DEFAULT_MANUSCRIPT_IMAGES path arithmetic).
DEFAULT_SI_TABLES_DIR = os.path.normpath(os.path.join(
    REPO_ROOT, "..", "..", "JCC", "JCC_SI", "tables"))

_LATEX_SPECIAL = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def _esc(val):
    """LaTeX-escape a single cell for a text column. NaN/None -> empty."""
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return ""
    return "".join(_LATEX_SPECIAL.get(ch, ch) for ch in str(val))


def _fmt(val, nd=3):
    """Numeric cell formatter: fixed `nd` decimal places, NaN/None -> empty."""
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return ""
    try:
        s = f"{float(val):.{nd}f}"
        return s[1:] if s.startswith("-") and float(s) == 0.0 else s  # no "-0.000"
    except (TypeError, ValueError):
        return _esc(val)


def _pack_bond_scores(row, bond_cols, nd=3):
    """Join per-bond `s_AB[A-B]` columns into one 'A-B:val; A-B:val' text
    cell (skips NaN entries) -- mirrors the packed `s_AB` string column
    already used by library_scores.csv."""
    parts = []
    for col in bond_cols:
        val = row[col]
        if pd.isna(val):
            continue
        bond = col.split("[", 1)[1].rstrip("]")
        parts.append(f"{bond}:{_fmt(val, nd)}")
    return "; ".join(parts)


def _write_longtable(rows, headers, col_spec, caption, label, out_path,
                      footnote=None, fontsize="\\small", landscape=False):
    """Write a booktabs-style `longtable` fragment. `rows` is a list of lists
    of already-formatted (escaped/rounded) strings; `headers` are already-
    escaped column headers; `col_spec` is the tabular column spec (e.g.
    'lrrl')."""
    ncol = len(headers)
    lines = ["% AUTO-GENERATED by src/si_tables.py / src/si_geometry_export.py -- do not edit by hand."]
    if landscape:
        lines.append("\\begin{landscape}  % requires \\usepackage{pdflscape}")
    lines.append("\\begingroup")
    lines.append(fontsize)
    lines.append("\\setlength{\\tabcolsep}{4pt}")
    lines.append(f"\\begin{{longtable}}{{{col_spec}}}")
    lines.append(f"\\caption{{{caption}}}\\label{{{label}}} \\\\")
    lines.append("\\toprule")
    header_row = " & ".join(headers) + r" \\"
    lines.append(header_row)
    lines.append("\\midrule")
    lines.append("\\endfirsthead")
    lines.append(f"\\multicolumn{{{ncol}}}{{l}}{{\\tablename\\ \\thetable{{}} -- "
                 "continued from previous page} \\\\")
    lines.append("\\toprule")
    lines.append(header_row)
    lines.append("\\midrule")
    lines.append("\\endhead")
    lines.append("\\midrule")
    lines.append(f"\\multicolumn{{{ncol}}}{{r}}{{continued on next page}} \\\\")
    lines.append("\\endfoot")
    lines.append("\\bottomrule")
    if footnote:
        lines.append(f"\\multicolumn{{{ncol}}}{{p{{0.95\\textwidth}}}}{{\\footnotesize {footnote}}} \\\\")
    lines.append("\\endlastfoot")
    for r in rows:
        lines.append(" & ".join(r) + r" \\")
    lines.append("\\end{longtable}")
    lines.append("\\endgroup")
    if landscape:
        lines.append("\\end{landscape}")
    text = "\n".join(lines) + "\n"

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)
    return out_path


_RAW_DATA_FOOTNOTE = (
    "Full raw score tables (including internal diagnostic columns not shown "
    "here) are available in the public code repository -- see the Data "
    "Availability Statement.")


def _write_column_block_table(mode_names, row_labels, data, caption, label,
                               out_path, footnote=None, fontsize="\\small",
                               landscape=True, modes_per_block=9, midrule_after=None):
    """Write a table with items as COLUMNS -- Table 4's own orientation --
    tiled across multiple fixed-size blocks stacked down the page, for a
    dataset with too many items to fit as columns in one block (36 EMIT
    modes at 9/block here) but too few rows for a longtable-style
    row-per-item layout to be the natural shape (see
    benzene_emit_summary_table). Not a `longtable`: each block is a plain
    `tabular`, since no single block's rows need multi-page continuation;
    `\\captionof{table}` (from the already-loaded `caption` package) gives it
    one shared, properly S-numbered caption/label without a floating `table`
    environment, which would not reliably hold multiple stacked blocks in
    place across a landscape page.

    mode_names : list of str, one per item (column), in order.
    row_labels : list of str, already LaTeX-ready (e.g. "$O[\\mathrm{T_x}]$").
    data : dict {mode_name: [formatted str, ...]}, one list per mode with
        one entry per row_labels, in the same order.
    midrule_after : int, optional -- 0-based row_labels index after which to
        insert an extra `\\midrule` inside each block (Table 4 itself has one
        between its O[...]/Ref.-mode block and its s[...]/Label block).
    """
    blocks = [mode_names[i:i + modes_per_block]
              for i in range(0, len(mode_names), modes_per_block)]

    lines = ["% AUTO-GENERATED by src/si_tables.py -- do not edit by hand."]
    if landscape:
        lines.append("\\begin{landscape}  % requires \\usepackage{pdflscape}")
    lines.append("\\begingroup")
    lines.append(fontsize)
    lines.append("\\setlength{\\tabcolsep}{5pt}")
    lines.append("\\begin{center}")
    lines.append(f"\\captionof{{table}}{{{caption}}}\\label{{{label}}}")
    lines.append("\\end{center}")

    for bi, block_modes in enumerate(blocks):
        if bi > 0:
            lines.append("\\bigskip")
            lines.append(f"\\centerline{{\\textit{{Table~\\ref{{{label}}} (continued).}}}}")
            lines.append("\\smallskip")
        col_spec = "l" + "c" * len(block_modes)
        lines.append("\\begin{center}")
        lines.append(f"\\begin{{tabular}}{{{col_spec}}}")
        lines.append("\\toprule")
        lines.append("Mode & " + " & ".join(_esc(m) for m in block_modes) + r" \\")
        lines.append("\\midrule")
        for ri, rlabel in enumerate(row_labels):
            cells = [data[m][ri] for m in block_modes]
            lines.append(rlabel + " & " + " & ".join(cells) + r" \\")
            if midrule_after is not None and ri == midrule_after:
                lines.append("\\midrule")
        lines.append("\\bottomrule")
        lines.append("\\end{tabular}")
        lines.append("\\end{center}")

    if footnote:
        lines.append("\\par\\smallskip\\noindent\\footnotesize " + footnote + "\\par")
    lines.append("\\endgroup")
    if landscape:
        lines.append("\\end{landscape}")
    text = "\n".join(lines) + "\n"

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)
    return out_path


# --- (A) Full score tables --------------------------------------------------

def water_table(data_dir=DEFAULT_DATA_DIR, out_dir=DEFAULT_SI_TABLES_DIR):
    """H2O_normal.csv -> tab_water_scores.tex (tab:waterscores). Extends the
    abbreviated main-text Table \\ref{tab:water} with per-bond s^{AB},
    reduced mass, and force constant."""
    df = pd.read_csv(os.path.join(data_dir, "results", "H2O_normal.csv"))
    bond_cols = [c for c in df.columns if c.startswith("s_AB[")]

    headers = ["Mode", "Freq (cm$^{-1}$)", "Predicted label", "Irrep",
               "$s[T_x]$", "$s[T_y]$", "$s[T_z]$",
               "$s[R_x]$", "$s[R_y]$", "$s[R_z]$", "$s[V_S]$",
               "$s^{AB}$ (bond:score)", "$\\mu$ (amu)", "$k$ (mDyn/\\AA)"]
    col_spec = "llllrrrrrrrlrr"

    rows = []
    for _, row in df.iterrows():
        pred = predicted_category(row["tr_label"], row["vib_label"])
        rows.append([
            _esc(row["Mode"]), _fmt(row["Freq"], 2), _esc(pred), _esc(row["Irrep"]),
            _fmt(row["Tx"]), _fmt(row["Ty"]), _fmt(row["Tz"]),
            _fmt(row["Rx"]), _fmt(row["Ry"]), _fmt(row["Rz"]), _fmt(row["V_Stretch"]),
            _esc(_pack_bond_scores(row, bond_cols)),
            _fmt(row["Mu"], 4), _fmt(row["K"], 4),
        ])

    caption = ("Full scoring table for the normal modes of H$_2$O -- extends the "
               "abbreviated Table~3 in the main text with per-bond "
               "$s^{AB}$ scores, reduced masses, and force constants.")
    return _write_longtable(rows, headers, col_spec, caption, "tab:waterscores",
                             os.path.join(out_dir, "tab_water_scores.tex"),
                             footnote=_RAW_DATA_FOOTNOTE)


def library_table(data_dir=DEFAULT_DATA_DIR, out_dir=DEFAULT_SI_TABLES_DIR):
    """library_scores.csv (85 molecules) -> tab_library_scores.tex
    (tab:libraryscores). Drops delta_b_mean/rel_db/has_geometry/ref_key/d_CA/
    v_weighting (debug/derivable columns)."""
    df = pd.read_csv(os.path.join(data_dir, "results", "library_scores.csv"))

    headers = ["Molecule", "Mode", "Kind", "Freq (cm$^{-1}$)", "Ref. label", "Ideal?",
               "Predicted label",
               "$s[T_x]$", "$s[T_y]$", "$s[T_z]$",
               "$s[R_x]$", "$s[R_y]$", "$s[R_z]$", "$s[V_S]$",
               "$s^{AB}$ (bond:score)", "$\\mu$ (amu)", "$k$ (mDyn/\\AA)", "Irrep"]
    col_spec = "lllrlll" + "rrrrrrr" + "lrrl"

    rows = []
    for _, row in df.iterrows():
        pred = predicted_category(row["predicted_tr_label"], row["predicted_vib_label"])
        rows.append([
            _esc(row["molecule"]), _esc(row["mode_index"]), _esc(row["kind"]),
            _fmt(row["freq"], 2), _esc(row["ref_label"]), _esc(row["ideal"]),
            _esc(pred),
            _fmt(row["Tx"]), _fmt(row["Ty"]), _fmt(row["Tz"]),
            _fmt(row["Rx"]), _fmt(row["Ry"]), _fmt(row["Rz"]), _fmt(row["V_Stretch"]),
            _esc(row["s_AB"]), _fmt(row["reduced_mass"], 4), _fmt(row["force_constant"], 4),
            _esc(row["irrep"]),
        ])

    caption = (f"Full scoring table for the {df['molecule'].nunique()}-molecule hydride "
               f"reference library ({len(df)} modes), including externals.")
    return _write_longtable(rows, headers, col_spec, caption, "tab:libraryscores",
                             os.path.join(out_dir, "tab_library_scores.tex"),
                             footnote=_RAW_DATA_FOOTNOTE, fontsize="\\scriptsize")


def benzene_normal_table(data_dir=DEFAULT_DATA_DIR, out_dir=DEFAULT_SI_TABLES_DIR):
    """C6H6_normal.csv -> tab_benzene_normal.tex (tab:benzenenormalscores)."""
    df = pd.read_csv(os.path.join(data_dir, "results", "C6H6_normal.csv"))
    bond_cols = [c for c in df.columns if c.startswith("s_AB[")]

    headers = ["Mode", "Freq (cm$^{-1}$)", "Predicted label", "Irrep",
               "$s[T_x]$", "$s[T_y]$", "$s[T_z]$",
               "$s[R_x]$", "$s[R_y]$", "$s[R_z]$", "$s[V_S]$",
               "$s^{AB}$ (bond:score)", "$\\mu$ (amu)", "$k$ (mDyn/\\AA)"]
    col_spec = "llllrrrrrrrlrr"

    rows = []
    for _, row in df.iterrows():
        pred = predicted_category(row["tr_label"], row["vib_label"])
        rows.append([
            _esc(row["Mode"]), _fmt(row["Freq"], 2), _esc(pred), _esc(row["Irrep"]),
            _fmt(row["Tx"]), _fmt(row["Ty"]), _fmt(row["Tz"]),
            _fmt(row["Rx"]), _fmt(row["Ry"]), _fmt(row["Rz"]), _fmt(row["V_Stretch"]),
            _esc(_pack_bond_scores(row, bond_cols)),
            _fmt(row["Mu"], 4), _fmt(row["K"], 4),
        ])

    caption = ("Full scoring table for the 36 normal modes of C$_6$H$_6$ (benzene), "
               "including the 12 per-bond $s^{AB}$ scores (6 C--C, 6 C--H).")
    return _write_longtable(rows, headers, col_spec, caption, "tab:benzenenormalscores",
                             os.path.join(out_dir, "tab_benzene_normal.tex"),
                             footnote=_RAW_DATA_FOOTNOTE, fontsize="\\scriptsize")


def benzene_emit_table(data_dir=DEFAULT_DATA_DIR, out_dir=DEFAULT_SI_TABLES_DIR):
    """C6H6_EMIT_full.csv -> tab_benzene_emit_full.tex (tab:benzeneemitscores).
    This is the raw eq:emitproj projection matrix (Tx..Rz + all 30 internal-
    vibration reference-basis components per EMIT mode) rather than the
    classify_all_modes summary in C6H6_EMIT.csv -- 38 columns, wrapped in a
    `landscape` block since it will not fit portrait even at \\tiny."""
    df = pd.read_csv(os.path.join(data_dir, "results", "C6H6_EMIT_full.csv"))
    vib_cols = [c for c in df.columns if c.startswith("Vib ")]

    headers = ["Mode", "Eigenvalue",
               "$s[T_x]$", "$s[T_y]$", "$s[T_z]$",
               "$s[R_x]$", "$s[R_y]$", "$s[R_z]$"] + [
        f"Vib {i}" for i in range(1, len(vib_cols) + 1)]
    col_spec = "lr" + "r" * 6 + "r" * len(vib_cols)

    rows = []
    for _, row in df.iterrows():
        rows.append([
            _esc(row["Mode"]), _fmt(row["Eigenvalue"], 2),
            _fmt(row["Tx"]), _fmt(row["Ty"]), _fmt(row["Tz"]),
            _fmt(row["Rx"]), _fmt(row["Ry"]), _fmt(row["Rz"]),
        ] + [_fmt(row[c]) for c in vib_cols])

    caption = ("Full EMIT-mode $\\to$ normal-mode projection matrix for C$_6$H$_6$ "
               "(Equation~\\ref{eq:emitproj}): projections of each of the 36 EMIT "
               "modes onto the 6 external ($T_x$--$R_z$) and 30 internal-vibration "
               "reference-basis vectors.")
    return _write_longtable(rows, headers, col_spec, caption, "tab:benzeneemitscores",
                             os.path.join(out_dir, "tab_benzene_emit_full.tex"),
                             footnote=_RAW_DATA_FOOTNOTE, fontsize="\\tiny",
                             landscape=True)


# --- (B) Benzene EMIT summary (all 36 modes, Table 4 format) ---------------

# Vib-N (internal 1..30 numbering used throughout this repo's CSVs, in
# ascending-frequency order -- see data/results/C6H6_normal.csv) -> literature
# Shimanouchi reference-mode number,\cite{Shi1972} raw LaTeX math ready to
# drop into a cell verbatim (NOT run through _esc()). Notation matches Table
# 4/tab:emitselected's own "Ref. mode" row exactly: italic Latin "v" (e.g.
# "$v_{13}$"), NOT the Greek "\nu" -- the main text's own LaTeX source uses
# "$v_{13}$", not "$\nu_{13}$", despite both being read aloud as "nu". ONLY
# the pairs independently established either by the main-text Table
# \ref{tab:benzenemixed} footnote (six "medium vibrational score" rows,
# matched by frequency) or by this module's own sanity check against the
# eight EMIT modes already published in Table \ref{tab:emitselected} (see
# si_tables benzene_emit_summary_table() docstring for the check and its one
# flagged discrepancy) are included here. Degenerate pairs (E1u/E2g/E1g, each
# spanning two adjacent Vib-N) share one reference-mode number, matching how
# the manuscript itself treats degenerate modes.
_BENZENE_VIB_TO_NU = {
    6: r"$v_{4}$",
    7: r"$v_{11}$", 8: r"$v_{11}$",
    13: r"$v_{14}$", 14: r"$v_{14}$",
    16: r"$v_{10}$",
    17: r"$v_{17}$", 18: r"$v_{17}$",
    19: r"$v_{9}$",
    21: r"$v_{13}$", 22: r"$v_{13}$",
    23: r"$v_{16}$", 24: r"$v_{16}$",
    26: r"$v_{15}$", 27: r"$v_{15}$",
    28: r"$v_{12}$", 29: r"$v_{12}$",
}


def benzene_emit_summary_table(data_dir=DEFAULT_DATA_DIR, out_dir=DEFAULT_SI_TABLES_DIR):
    """All 36 EMIT modes of C6H6 in the same per-mode format as the main
    text's 8-mode Table \\ref{tab:emitselected} -- tab_benzene_emit_summary.tex
    (tab:benzeneemitsummary).

    Column sourcing, per mode:
      O[Tx..Rz]   <- data/results/C6H6_EMIT.csv "Ocart_Tx".."Ocart_Rz"
                     (src.projection.project_emit_cartesian's raw signed,
                     plain-Cartesian overlap; see the sanity-check note below
                     for why this pathway, not the mass-weighted eq:emitproj
                     one, is the one that reproduces Table 4/tab:emitselected).
      O[vm], Vib N <- data/results/C6H6_EMIT_full_cartesian.csv "Vib 1".."Vib
                     30" (same plain-Cartesian pathway's per-reference-mode
                     detail): the signed value of largest magnitude and its
                     index.
      nu (lit.)   <- _BENZENE_VIB_TO_NU, keyed on that Vib-N index; blank for
                     every Vib-N not in the dict (no fabricated assignments).
      s[Tx..Rz], s[Vs], Label, T/R label
                  <- data/results/C6H6_EMIT.csv "Tx".."Rz" (classify_all_modes'
                     own scores, distinct from the Ocart_* overlap columns
                     above despite the shared "Tx" name), "V_Stretch",
                     "vib_label", "tr_label" (blank -> "-").

    Sanity check performed during development (per the task that added this
    function): for the 8 modes already published in Table
    \\ref{tab:emitselected} (EMIT 34,35,36,18,13,19,16,33), O[Tx..Rz], s[Tx..
    Rz], and |O[vm]| all reproduce the published values to ~0.01 using the
    plain-Cartesian "Ocart_*"/project_emit_cartesian() pathway -- e.g. EMIT
    34's Ocart_Tx=0.876 matches the published O[Tx]=0.88, matching
    IMPLEMENTATION_PLAN.md's own pinned ground truth for that value; EMIT 18's
    Ocart_Rx=-0.680 matches O[Rx]=-0.68 and its top Vib-8 overlap (-0.721)
    matches O[vm]=-0.72 (Ref. mode v11). The mass-weighted eq:emitproj
    pathway (src.projection.project_emit's Theta_tilde, squared into the
    "C2_*" columns) does NOT reproduce these numbers (e.g. its unsquared
    signed value for EMIT 18's Rx-overlap comes out -0.357, not -0.68) --
    expected, since Table \\ref{tab:emitselected}'s own caption states it
    projects onto "Cartesian normal coordinates", i.e. the unweighted
    pathway. This function therefore deliberately joins against
    Ocart_*/EMIT_full_cartesian.csv (already produced by the existing
    project_emit_cartesian() call in main.run_projection_pipeline -- no new
    projection logic was needed), so the SI table's 8 previously-published
    rows stay numerically identical to the main text.
    NOTE (flagged, not fixed here): JCC_SI_main.tex si:projection currently
    frames the mass-weighted pathway as primary and the Cartesian one as "a
    diagnostic point of comparison ... not used as an alternative to
    Equation (eq:emitproj) in any of the results reported in the main text"
    -- that description is now stale, since Table 4/tab:emitselected's O[...]
    values ARE the Cartesian pathway's output. Left for lead-author to
    reconcile the prose; not touched by this function.
    One discrepancy remains unresolved and is NOT papered over: EMIT 19's
    published Ref. mode is v13, but v13 is independently pinned (via
    EMIT 34/35 and the tab:benzenemixed footnote) to Vib 21/22 (E1u, 1532.85
    cm^-1) -- EMIT 19 actually has ~0 overlap with those two normal modes.
    EMIT 19's true largest-magnitude overlap is Vib 20 (A2g, 1435.48 cm^-1,
    value 0.743, matching the published O[vm]=0.74 in magnitude), which is
    symmetry-consistent (Rz transforms as A2g in D6h) but has no established
    literature nu-number in this study's data -- likely a labeling
    transcription slip in the main text rather than a data-regeneration
    issue, since every one of EMIT 19's other published numbers (O[Rz]=0.65,
    s[Rz]=0.33, etc.) matches exactly. _BENZENE_VIB_TO_NU is left without a
    Vib-20 entry rather than propagating that label, so this row's "nu (lit.)"
    cell comes out blank automatically -- consistent with the "no fabricated
    assignments" rule below.
    """
    df = pd.read_csv(os.path.join(data_dir, "results", "C6H6_EMIT.csv"))
    df_full = pd.read_csv(os.path.join(data_dir, "results", "C6H6_EMIT_full_cartesian.csv"))
    vib_cols = [c for c in df_full.columns if c.startswith("Vib ")]
    full_by_mode = {row["Mode"]: row for _, row in df_full.iterrows()}

    # T_x/R_x/V_S set in \mathrm{} (upright, per the main text's own
    # "$O[\mathrm{T_x}]$"/"$s[\mathrm{T_x}]$"), so they no longer render in
    # math-italic the way a bare "$o[T_x]$" would. Overlap notation uses
    # lowercase "o" here (not Table 4's own capital "O") -- an intentional
    # departure from Table 4, per explicit request. "Ref. mode" is Table 4's
    # own row (literature Shimanouchi numbering, italic Latin "v" per
    # _BENZENE_VIB_TO_NU above); the internal Vib-N index used to find it
    # (best_col below) is not itself shown as its own row here.
    row_labels = ["Eigenvalue",
                  "$o[\\mathrm{T_x}]$", "$o[\\mathrm{T_y}]$", "$o[\\mathrm{T_z}]$",
                  "$o[\\mathrm{R_x}]$", "$o[\\mathrm{R_y}]$", "$o[\\mathrm{R_z}]$", "$o[v_m]$",
                  "Ref. mode\\cite{Shi1972}", "\\%$\\nu$",
                  "$s[\\mathrm{T_x}]$", "$s[\\mathrm{T_y}]$", "$s[\\mathrm{T_z}]$",
                  "$s[\\mathrm{R_x}]$", "$s[\\mathrm{R_y}]$", "$s[\\mathrm{R_z}]$", "$s[\\mathrm{V_S}]$",
                  "Label", "T/R label"]
    # Index (0-based) of the last row before the s[...] block starts, for the
    # extra \midrule Table 4 itself has between its o[...]/Ref.-mode block
    # and its s[...]/Label/T-R-label block.
    _MIDRULE_AFTER = 9

    # %nu: this study's own real PED analysis (VEDA4, via ped/merge_ped_scores.py
    # -- see JCC_SI_main.tex si:ped), already merged into C6H6_normal.csv's
    # "PED_Stretch_pct" column and keyed on the same "Vib N" identifier as
    # best_col below -- no re-derivation or fresh frequency-matching needed.
    # Every one of benzene's 30 normal modes has a PED row (unlike the sparse
    # literature nu-numbering above), so this is never blank. Values can
    # exceed 100 (e.g. 108) -- expected for this redundant-coordinate PED set,
    # not a bug (see merge_ped_scores.py's module docstring).
    df_normal = pd.read_csv(os.path.join(data_dir, "results", "C6H6_normal.csv"))
    pednu_by_vib = dict(zip(df_normal["Mode"], df_normal["PED_Stretch_pct"]))

    mode_names = []
    data = {}
    for _, row in df.iterrows():
        mode = row["Mode"]
        full_row = full_by_mode[mode]
        vib_vals = full_row[vib_cols].astype(float)
        best_col = vib_vals.abs().idxmax()
        best_val = vib_vals[best_col]
        vib_n = int(best_col.split(" ")[1])
        nu_lit = _BENZENE_VIB_TO_NU.get(vib_n, "")
        pednu_cell = _fmt(pednu_by_vib.get(best_col), 0)

        tr_label = row["tr_label"]
        tr_cell = "-" if pd.isna(tr_label) or str(tr_label).strip() == "" else _esc(tr_label)

        mode_names.append(mode)
        data[mode] = [
            _fmt(row["Eigenvalue"], 2),
            _fmt(row["Ocart_Tx"]), _fmt(row["Ocart_Ty"]), _fmt(row["Ocart_Tz"]),
            _fmt(row["Ocart_Rx"]), _fmt(row["Ocart_Ry"]), _fmt(row["Ocart_Rz"]),
            _fmt(best_val), nu_lit, pednu_cell,
            _fmt(row["Tx"]), _fmt(row["Ty"]), _fmt(row["Tz"]),
            _fmt(row["Rx"]), _fmt(row["Ry"]), _fmt(row["Rz"]), _fmt(row["V_Stretch"]),
            _esc(row["vib_label"]), tr_cell,
        ]

    footnote = (
        "$o$ denotes an overlap from each type of normal modes, including "
        "translation [T], rotation [R], and the highest-overlapped "
        "vibrational mode(s) [$v_m$]. Blank Ref.-mode cells are modes "
        "without a published Shimanouchi assignment in this study. "
        "\\%$\\nu$ is the real VEDA4 PED-derived total stretching "
        "contribution (Section~\\ref{si:ped}) of the matched Vib-$N$ normal "
        "mode; values above 100 reflect this molecule's redundant internal- "
        "coordinate set and are not an error. "
        + _RAW_DATA_FOOTNOTE)
    caption = ("Full listing of all 36 EMIT modes of C$_6$H$_6$ (benzene), tiled in "
               "the same per-mode-as-column format as the main text's 8-mode Table~4 "
               "(\\texttt{tab:emitselected}), extended here to the complete EMIT "
               "eigenbasis.")
    return _write_column_block_table(mode_names, row_labels, data, caption,
                                      "tab:benzeneemitsummary",
                                      os.path.join(out_dir, "tab_benzene_emit_summary.tex"),
                                      footnote=footnote, fontsize="\\footnotesize",
                                      landscape=True, modes_per_block=12,
                                      midrule_after=_MIDRULE_AFTER)


def transferability_misclassified_table(data_dir=DEFAULT_DATA_DIR, out_dir=DEFAULT_SI_TABLES_DIR):
    """transferability_confusion_misclassified.csv -> tab_transferability_misclassified.tex
    (tab:transfermisclassified). Full mode-by-mode listing of the 17 modes
    off the diagonal of Figure~\\ref{fig:transferability_confusion}'s S/B
    confusion matrix, with the literature description and source tag that
    justify the reference label. `ref` values (e.g. "Lip1955") are NOT yet
    entries in MolecularMotion.bib -- bibtex confirmed they're undefined --
    so they're emitted as escaped plain text, not `\\cite{}`, to avoid an
    undefined-citation warning and fabricated bibliography entries. Promote
    to `\\cite{}` once real entries exist for these keys."""
    df = pd.read_csv(os.path.join(data_dir, "results",
                                   "transferability_confusion_misclassified.csv"))

    headers = ["Molecule", "Mode", "Freq (cm$^{-1}$)", "Irrep", "$s[V_S]$",
               "Ref. category", "Predicted", "Description", "Ref."]
    col_spec = "llrlrllll"

    rows = []
    for _, row in df.iterrows():
        rows.append([
            _esc(row["molecule"]), _esc(row["mode_index"]),
            _fmt(row["freq"], 2), _esc(row["irrep"]), _fmt(row["V_Stretch"]),
            _esc(row["ref_category"]), _esc(row["predicted_label"]),
            _esc(row["description"]), _esc(row["ref"]),
        ])

    caption = (f"Mode-by-mode listing of the {len(df)} modes misclassified against "
               "literature reference labels in the 18-molecule transferability test "
               "set (off-diagonal entries of the main text's Figure~6, "
               "\\texttt{fig:transferability\\_confusion}, stretch/bend confusion "
               "matrix), with the literature description and source justifying each "
               "reference label.")
    return _write_longtable(rows, headers, col_spec, caption, "tab:transfermisclassified",
                             os.path.join(out_dir, "tab_transferability_misclassified.tex"),
                             footnote=_RAW_DATA_FOOTNOTE)


def run_all(data_dir=DEFAULT_DATA_DIR, out_dir=DEFAULT_SI_TABLES_DIR):
    return [
        water_table(data_dir, out_dir),
        library_table(data_dir, out_dir),
        benzene_normal_table(data_dir, out_dir),
        benzene_emit_table(data_dir, out_dir),
        benzene_emit_summary_table(data_dir, out_dir),
        transferability_misclassified_table(data_dir, out_dir),
    ]


if __name__ == "__main__":
    for p in run_all():
        print(p)
