"""Generate longtable LaTeX fragments for the JCC Supporting Information from
the program's own data/results/*.csv -- for lead-author's JCC_SI_main.tex to
\\input{}. Pure formatting: no new scoring/classification logic and no
recomputation, every number here already exists in a results CSV.

    python -m src.si_tables            # regenerate all four fragments

One function per dataset (`water_table`, `library_table`,
`benzene_normal_table`, `benzene_emit_table`), each:
  1. reads the corresponding CSV with pandas,
  2. trims to a human-readable column subset -- molecule/mode label, freq,
     predicted label, the relevant s[T]/s[R]/s[V_S]/s^{AB} scores, irrep --
     dropping internal/debug columns (d_CA, v_weighting, ref_key, PED_*,
     BondScore_*; full raw CSVs stay in the public repo per the Data
     Availability Statement, noted as a table footnote),
  3. writes a booktabs-style `longtable` fragment (with \\endfirsthead/
     \\endhead for multi-page continuation) to JCC/JCC_SI/tables/.

The master document must load `longtable`, `booktabs`, and (for the
benzene-EMIT fragment, which is wrapped in a `landscape` block -- 38 columns
do not fit portrait even at \\tiny) `pdflscape`.
"""

import os
import pandas as pd

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_DATA_DIR = os.path.join(REPO_ROOT, "data")
# Two levels up from Github/scoring-functions/ is the OneDrive project root
# (mirrors reproduce.py's DEFAULT_MANUSCRIPT_IMAGES path arithmetic).
DEFAULT_SI_TABLES_DIR = os.path.normpath(os.path.join(
    REPO_ROOT, "..", "..", "JCC", "JCC_SI", "tables"))

_LATEX_SPECIAL = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def _esc(val):
    """LaTeX-escape a single cell for a text column. NaN/None -> empty."""
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return ""
    return "".join(_LATEX_SPECIAL.get(ch, ch) for ch in str(val))


def _fmt(val, nd=3):
    """Numeric cell formatter: fixed `nd` decimal places, NaN/None -> empty."""
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return ""
    try:
        s = f"{float(val):.{nd}f}"
        return s[1:] if s.startswith("-") and float(s) == 0.0 else s  # no "-0.000"
    except (TypeError, ValueError):
        return _esc(val)


def _pack_bond_scores(row, bond_cols, nd=3):
    """Join per-bond `s_AB[A-B]` columns into one 'A-B:val; A-B:val' text
    cell (skips NaN entries) -- mirrors the packed `s_AB` string column
    already used by library_scores.csv."""
    parts = []
    for col in bond_cols:
        val = row[col]
        if pd.isna(val):
            continue
        bond = col.split("[", 1)[1].rstrip("]")
        parts.append(f"{bond}:{_fmt(val, nd)}")
    return "; ".join(parts)


def _write_longtable(rows, headers, col_spec, caption, label, out_path,
                      footnote=None, fontsize="\\small", landscape=False):
    """Write a booktabs-style `longtable` fragment. `rows` is a list of lists
    of already-formatted (escaped/rounded) strings; `headers` are already-
    escaped column headers; `col_spec` is the tabular column spec (e.g.
    'lrrl')."""
    ncol = len(headers)
    lines = ["% AUTO-GENERATED by src/si_tables.py / src/si_geometry_export.py -- do not edit by hand."]
    if landscape:
        lines.append("\\begin{landscape}  % requires \\usepackage{pdflscape}")
    lines.append("\\begingroup")
    lines.append(fontsize)
    lines.append("\\setlength{\\tabcolsep}{4pt}")
    lines.append(f"\\begin{{longtable}}{{{col_spec}}}")
    lines.append(f"\\caption{{{caption}}}\\label{{{label}}} \\\\")
    lines.append("\\toprule")
    header_row = " & ".join(headers) + r" \\"
    lines.append(header_row)
    lines.append("\\midrule")
    lines.append("\\endfirsthead")
    lines.append(f"\\multicolumn{{{ncol}}}{{l}}{{\\tablename\\ \\thetable{{}} -- "
                 "continued from previous page} \\\\")
    lines.append("\\toprule")
    lines.append(header_row)
    lines.append("\\midrule")
    lines.append("\\endhead")
    lines.append("\\midrule")
    lines.append(f"\\multicolumn{{{ncol}}}{{r}}{{continued on next page}} \\\\")
    lines.append("\\endfoot")
    lines.append("\\bottomrule")
    if footnote:
        lines.append(f"\\multicolumn{{{ncol}}}{{p{{0.95\\textwidth}}}}{{\\footnotesize {footnote}}} \\\\")
    lines.append("\\endlastfoot")
    for r in rows:
        lines.append(" & ".join(r) + r" \\")
    lines.append("\\end{longtable}")
    lines.append("\\endgroup")
    if landscape:
        lines.append("\\end{landscape}")
    text = "\n".join(lines) + "\n"

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)
    return out_path


_RAW_DATA_FOOTNOTE = (
    "Full raw score tables (including internal diagnostic columns not shown "
    "here) are available in the public code repository -- see the Data "
    "Availability Statement.")


# --- (A) Full score tables --------------------------------------------------

def water_table(data_dir=DEFAULT_DATA_DIR, out_dir=DEFAULT_SI_TABLES_DIR):
    """H2O_normal.csv -> tab_water_scores.tex (tab:waterscores). Extends the
    abbreviated main-text Table \\ref{tab:water} with per-bond s^{AB},
    reduced mass, and force constant."""
    df = pd.read_csv(os.path.join(data_dir, "results", "H2O_normal.csv"))
    bond_cols = [c for c in df.columns if c.startswith("s_AB[")]

    headers = ["Mode", "Freq (cm$^{-1}$)", "Predicted label", "Irrep",
               "$s[T_x]$", "$s[T_y]$", "$s[T_z]$",
               "$s[R_x]$", "$s[R_y]$", "$s[R_z]$", "$s[V_S]$",
               "$s^{AB}$ (bond:score)", "$\\mu$ (amu)", "$k$ (mDyn/\\AA)"]
    col_spec = "llllrrrrrrrlrr"

    rows = []
    for _, row in df.iterrows():
        rows.append([
            _esc(row["Mode"]), _fmt(row["Freq"], 2), _esc(row["label"]), _esc(row["Irrep"]),
            _fmt(row["Tx"]), _fmt(row["Ty"]), _fmt(row["Tz"]),
            _fmt(row["Rx"]), _fmt(row["Ry"]), _fmt(row["Rz"]), _fmt(row["V_Stretch"]),
            _esc(_pack_bond_scores(row, bond_cols)),
            _fmt(row["Mu"], 4), _fmt(row["K"], 4),
        ])

    caption = ("Full scoring table for the normal modes of H$_2$O -- extends the "
               "abbreviated Table~3 in the main text with per-bond "
               "$s^{AB}$ scores, reduced masses, and force constants.")
    return _write_longtable(rows, headers, col_spec, caption, "tab:waterscores",
                             os.path.join(out_dir, "tab_water_scores.tex"),
                             footnote=_RAW_DATA_FOOTNOTE)


def library_table(data_dir=DEFAULT_DATA_DIR, out_dir=DEFAULT_SI_TABLES_DIR):
    """library_scores.csv (85 molecules) -> tab_library_scores.tex
    (tab:libraryscores). Drops delta_b_mean/rel_db/has_geometry/ref_key/d_CA/
    v_weighting (debug/derivable columns)."""
    df = pd.read_csv(os.path.join(data_dir, "results", "library_scores.csv"))

    headers = ["Molecule", "Mode", "Kind", "Freq (cm$^{-1}$)", "Ref. label", "Ideal?",
               "Predicted label",
               "$s[T_x]$", "$s[T_y]$", "$s[T_z]$",
               "$s[R_x]$", "$s[R_y]$", "$s[R_z]$", "$s[V_S]$",
               "$s^{AB}$ (bond:score)", "$\\mu$ (amu)", "$k$ (mDyn/\\AA)", "Irrep"]
    col_spec = "lllrlll" + "rrrrrrr" + "lrrl"

    rows = []
    for _, row in df.iterrows():
        rows.append([
            _esc(row["molecule"]), _esc(row["mode_index"]), _esc(row["kind"]),
            _fmt(row["freq"], 2), _esc(row["ref_label"]), _esc(row["ideal"]),
            _esc(row["predicted_label"]),
            _fmt(row["Tx"]), _fmt(row["Ty"]), _fmt(row["Tz"]),
            _fmt(row["Rx"]), _fmt(row["Ry"]), _fmt(row["Rz"]), _fmt(row["V_Stretch"]),
            _esc(row["s_AB"]), _fmt(row["reduced_mass"], 4), _fmt(row["force_constant"], 4),
            _esc(row["irrep"]),
        ])

    caption = (f"Full scoring table for the {df['molecule'].nunique()}-molecule hydride "
               f"reference library ({len(df)} modes), including externals.")
    return _write_longtable(rows, headers, col_spec, caption, "tab:libraryscores",
                             os.path.join(out_dir, "tab_library_scores.tex"),
                             footnote=_RAW_DATA_FOOTNOTE, fontsize="\\scriptsize")


def benzene_normal_table(data_dir=DEFAULT_DATA_DIR, out_dir=DEFAULT_SI_TABLES_DIR):
    """C6H6_normal.csv -> tab_benzene_normal.tex (tab:benzenenormalscores)."""
    df = pd.read_csv(os.path.join(data_dir, "results", "C6H6_normal.csv"))
    bond_cols = [c for c in df.columns if c.startswith("s_AB[")]

    headers = ["Mode", "Freq (cm$^{-1}$)", "Predicted label", "Irrep",
               "$s[T_x]$", "$s[T_y]$", "$s[T_z]$",
               "$s[R_x]$", "$s[R_y]$", "$s[R_z]$", "$s[V_S]$",
               "$s^{AB}$ (bond:score)", "$\\mu$ (amu)", "$k$ (mDyn/\\AA)"]
    col_spec = "llllrrrrrrrlrr"

    rows = []
    for _, row in df.iterrows():
        rows.append([
            _esc(row["Mode"]), _fmt(row["Freq"], 2), _esc(row["label"]), _esc(row["Irrep"]),
            _fmt(row["Tx"]), _fmt(row["Ty"]), _fmt(row["Tz"]),
            _fmt(row["Rx"]), _fmt(row["Ry"]), _fmt(row["Rz"]), _fmt(row["V_Stretch"]),
            _esc(_pack_bond_scores(row, bond_cols)),
            _fmt(row["Mu"], 4), _fmt(row["K"], 4),
        ])

    caption = ("Full scoring table for the 36 normal modes of C$_6$H$_6$ (benzene), "
               "including the 12 per-bond $s^{AB}$ scores (6 C--C, 6 C--H).")
    return _write_longtable(rows, headers, col_spec, caption, "tab:benzenenormalscores",
                             os.path.join(out_dir, "tab_benzene_normal.tex"),
                             footnote=_RAW_DATA_FOOTNOTE, fontsize="\\scriptsize")


def benzene_emit_table(data_dir=DEFAULT_DATA_DIR, out_dir=DEFAULT_SI_TABLES_DIR):
    """C6H6_EMIT_full.csv -> tab_benzene_emit_full.tex (tab:benzeneemitscores).
    This is the raw eq:emitproj projection matrix (Tx..Rz + all 30 internal-
    vibration reference-basis components per EMIT mode) rather than the
    classify_all_modes summary in C6H6_EMIT.csv -- 38 columns, wrapped in a
    `landscape` block since it will not fit portrait even at \\tiny."""
    df = pd.read_csv(os.path.join(data_dir, "results", "C6H6_EMIT_full.csv"))
    vib_cols = [c for c in df.columns if c.startswith("Vib ")]

    headers = ["Mode", "Eigenvalue",
               "$s[T_x]$", "$s[T_y]$", "$s[T_z]$",
               "$s[R_x]$", "$s[R_y]$", "$s[R_z]$"] + [
        f"Vib {i}" for i in range(1, len(vib_cols) + 1)]
    col_spec = "lr" + "r" * 6 + "r" * len(vib_cols)

    rows = []
    for _, row in df.iterrows():
        rows.append([
            _esc(row["Mode"]), _fmt(row["Eigenvalue"], 2),
            _fmt(row["Tx"]), _fmt(row["Ty"]), _fmt(row["Tz"]),
            _fmt(row["Rx"]), _fmt(row["Ry"]), _fmt(row["Rz"]),
        ] + [_fmt(row[c]) for c in vib_cols])

    caption = ("Full EMIT-mode $\\to$ normal-mode projection matrix for C$_6$H$_6$ "
               "(Equation~\\ref{eq:emitproj}): projections of each of the 36 EMIT "
               "modes onto the 6 external ($T_x$--$R_z$) and 30 internal-vibration "
               "reference-basis vectors.")
    return _write_longtable(rows, headers, col_spec, caption, "tab:benzeneemitscores",
                             os.path.join(out_dir, "tab_benzene_emit_full.tex"),
                             footnote=_RAW_DATA_FOOTNOTE, fontsize="\\tiny",
                             landscape=True)


def transferability_misclassified_table(data_dir=DEFAULT_DATA_DIR, out_dir=DEFAULT_SI_TABLES_DIR):
    """transferability_confusion_misclassified.csv -> tab_transferability_misclassified.tex
    (tab:transfermisclassified). Full mode-by-mode listing of the 17 modes
    off the diagonal of Figure~\\ref{fig:transferability_confusion}'s S/B
    confusion matrix, with the literature description and source tag that
    justify the reference label. `ref` values (e.g. "Lip1955") are NOT yet
    entries in MolecularMotion.bib -- bibtex confirmed they're undefined --
    so they're emitted as escaped plain text, not `\\cite{}`, to avoid an
    undefined-citation warning and fabricated bibliography entries. Promote
    to `\\cite{}` once real entries exist for these keys."""
    df = pd.read_csv(os.path.join(data_dir, "results",
                                   "transferability_confusion_misclassified.csv"))

    headers = ["Molecule", "Mode", "Freq (cm$^{-1}$)", "Irrep", "$s[V_S]$",
               "Ref. category", "Predicted", "Description", "Ref."]
    col_spec = "llrlrllll"

    rows = []
    for _, row in df.iterrows():
        rows.append([
            _esc(row["molecule"]), _esc(row["mode_index"]),
            _fmt(row["freq"], 2), _esc(row["irrep"]), _fmt(row["V_Stretch"]),
            _esc(row["ref_category"]), _esc(row["predicted_label"]),
            _esc(row["description"]), _esc(row["ref"]),
        ])

    caption = (f"Mode-by-mode listing of the {len(df)} modes misclassified against "
               "literature reference labels in the 18-molecule transferability test "
               "set (off-diagonal entries of the main text's Figure~6, "
               "\\texttt{fig:transferability\\_confusion}, stretch/bend confusion "
               "matrix), with the literature description and source justifying each "
               "reference label.")
    return _write_longtable(rows, headers, col_spec, caption, "tab:transfermisclassified",
                             os.path.join(out_dir, "tab_transferability_misclassified.tex"),
                             footnote=_RAW_DATA_FOOTNOTE)


def run_all(data_dir=DEFAULT_DATA_DIR, out_dir=DEFAULT_SI_TABLES_DIR):
    return [
        water_table(data_dir, out_dir),
        library_table(data_dir, out_dir),
        benzene_normal_table(data_dir, out_dir),
        benzene_emit_table(data_dir, out_dir),
        transferability_misclassified_table(data_dir, out_dir),
    ]


if __name__ == "__main__":
    for p in run_all():
        print(p)
